# Artificial Neural Networks (ANN)

**1. Data Preprocessing**

In [52]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [53]:
import warnings
warnings.filterwarnings('ignore')

In [54]:
dataframe = pd.read_csv('Churn_Modelling.csv')
dataframe.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [55]:
X = dataframe.iloc[:, 3:-1].values
y = dataframe.iloc[:, -1].values

**1.1. Encoding Categorical Data**

In [56]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

**Gender:**

In [57]:
label_encoder = LabelEncoder()

In [58]:
X[:, 2] = label_encoder.fit_transform(X[:, 2])

**Geography:**

In [59]:
column_transformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')

In [60]:
X = np.array(column_transformer.fit_transform(X))

In [61]:
# Remove one column to prevent dummy trap
# But libraries handle this
# X = X[:, 1:]

In [63]:
X[:5, :]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

**1.2. Feature Scaling**

In [64]:
from sklearn.preprocessing import StandardScaler

In [65]:
sc = StandardScaler()
X = sc.fit_transform(X)

**1.3. Splitting Data to Training Set and Test Set**

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

**2. Artificial Neural Network**

**Step 1: Create Neural Network**

**Intializing the ANN**

In [68]:
ann = tf.keras.models.Sequential()

**Adding the Input Layer and the First Hidden Layer**

In [69]:
# number of units is ART, and you have to experiment and choose different number of units to get the best model
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the Second Hidden Layer**

In [70]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the Output Layer**

In [71]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

**Step 2: Training the ANN**

**Compile**

In [72]:
# Stochastic gradient descent optimizer: adam
# Logarithmic Loss:
# if dependent variable has binary outcome, Logarithmic Loss = binary cross entropy loss
# if dependent variable has more than two outcome, Logarithmic Loss = categorical cross entropy loss 
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**Training on the Training Set**

In [73]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 117us/sample - loss: 0.6284 - accuracy: 0.7145
Epoch 2/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.4850 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 63us/sample - loss: 0.4509 - accuracy: 0.7969
Epoch 4/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.4347 - accuracy: 0.8056
Epoch 5/100
8000/8000 [==============================] - 1s 68us/sample - loss: 0.4266 - accuracy: 0.8125
Epoch 6/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.4219 - accuracy: 0.8161
Epoch 7/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.4196 - accuracy: 0.8176
Epoch 8/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4174 - accuracy: 0.8207
Epoch 9/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.4156 - accuracy: 0.8229
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 1s 75us/sample - loss: 0.3350 - accuracy: 0.8605
Epoch 78/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.3349 - accuracy: 0.8611
Epoch 79/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.3348 - accuracy: 0.8614
Epoch 80/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.3343 - accuracy: 0.8627
Epoch 81/100
8000/8000 [==============================] - 1s 79us/sample - loss: 0.3343 - accuracy: 0.8610
Epoch 82/100
8000/8000 [==============================] - 1s 65us/sample - loss: 0.3347 - accuracy: 0.8614
Epoch 83/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3345 - accuracy: 0.8609
Epoch 84/100
8000/8000 [==============================] - 0s 47us/sample - loss: 0.3342 - accuracy: 0.8612
Epoch 85/100
8000/8000 [==============================] - 1s 63us/sample - loss: 0.3342 - accuracy: 0.8615
Epoch 86/100
8000/8000 [==========================

**3. Use ANN model to predict if the customer with the following informations will leave the bank:**

**- Ceography:** France<br>
**- Credit Score:** 600<br>
**- Gender:** Male<br>
**- Age:** 40<br>
**- Tenure:** 3 years<br>
**- Balance:** 60000<br>
**- Number of Products:** 2<br>
**- Does this customer have a credit cart?** Yes<br>
**- Is this customer an active member?** Yes<br>
**- Estimate Salary:** $ 50000<br>

**So, should we say goodbye to that customer or not?**

In [93]:
example_predict = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
print('probability: {}'.format(example_predict[0][0]))
print('final answer: {}'.format(example_predict[0][0]>0.5))

probability: 0.023626970127224922
final answer: False


**4. Evaluating the Model**

In [94]:
y_predict = ann.predict(x_test)
y_predict[:6]

array([[0.2768205 ],
       [0.33978817],
       [0.12055765],
       [0.03941661],
       [0.051199  ],
       [0.83619744]], dtype=float32)

In [95]:
# Change probability to binary value
y_predict = (y_predict > 0.5)
np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)), 1)

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [102]:
y_predict

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
tn, fp, fn, tp = confusion_matrix(y_test, y_predict).ravel()
confusion_matrix(y_test, y_predict)

array([[1504,   91],
       [ 179,  226]], dtype=int64)

In [26]:
accuracy = (tn + tp) / (tn + fp + fn + tp)
precision = tp / (fp + tp)
recall = tp / (fn + tp)
f1_score = (2 * precision * recall) / (precision + recall)

In [27]:
print('Accuracy: {}'.format(accuracy))
print('Precision: {}'.format(precision))
print('Recall: {}'.format(recall))
print('F1 Score: {}'.format(f1_score))

Accuracy: 0.865
Precision: 0.7129337539432177
Recall: 0.5580246913580247
F1 Score: 0.6260387811634349
