# Artificial Neural Networks (ANN)

**1. Data Preprocessing**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
dataframe = pd.read_csv('Churn_Modelling.csv')
dataframe.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataframe.iloc[:, 3:-1].values
y = dataframe.iloc[:, -1].values

**1.1. Encoding Categorical Data**

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

**Gender:**

In [6]:
label_encoder = LabelEncoder()

In [7]:
X[:, 2] = label_encoder.fit_transform(X[:, 2])

**Geography:**

In [8]:
column_transformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')

In [9]:
X = np.array(column_transformer.fit_transform(X))

In [10]:
# Remove one column to prevent dummy trap
# But libraries handle this
X = X[:, 1:]

In [11]:
pd.DataFrame(X[:5, :])

0  1    2  3   4  5        6  7  8  9        10
0  0  0  619  0  42  2        0  1  1  1   101349
1  0  1  608  0  41  1  83807.9  1  0  1   112543
2  0  0  502  0  42  8   159661  3  1  0   113932
3  0  0  699  0  39  1        0  2  0  0  93826.6
4  0  1  850  0  43  2   125511  1  1  1  79084.1

**1.2. Feature Scaling**

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()
X = sc.fit_transform(X)

**1.3. Splitting Data to Training Set and Test Set**

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

**2. Artificial Neural Network**

**Step 1: Create Neural Network**

**Intializing the ANN**

In [16]:
ann = tf.keras.models.Sequential()

**Adding the Input Layer and the First Hidden Layer**

In [17]:
# number of units is ART, and you have to experiment and choose different number of units to get the best model
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the Second Hidden Layer**

In [18]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the Output Layer**

In [19]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

**Step 2: Training the ANN**

**Compile**

In [20]:
# Stochastic gradient descent optimizer: adam
# Logarithmic Loss:
# if dependent variable has binary outcome, Logarithmic Loss = binary cross entropy loss
# if dependent variable has more than two outcome, Logarithmic Loss = categorical cross entropy loss 
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**Training on the Training Set**

In [21]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 139us/sample - loss: 0.5196 - accuracy: 0.7911
Epoch 2/100
8000/8000 [==============================] - 1s 66us/sample - loss: 0.4630 - accuracy: 0.7966
Epoch 3/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4423 - accuracy: 0.8036
Epoch 4/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4303 - accuracy: 0.8080
Epoch 5/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.4225 - accuracy: 0.8099
Epoch 6/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4159 - accuracy: 0.8150
Epoch 7/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.4094 - accuracy: 0.8192
Epoch 8/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4028 - accuracy: 0.8249
Epoch 9/100
8000/8000 [==============================] - 1s 68us/sample - loss: 0.3958 - accuracy: 0.8294
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 1s 68us/sample - loss: 0.3292 - accuracy: 0.8645
Epoch 78/100
8000/8000 [==============================] - 1s 68us/sample - loss: 0.3294 - accuracy: 0.8651
Epoch 79/100
8000/8000 [==============================] - 0s 60us/sample - loss: 0.3288 - accuracy: 0.8645
Epoch 80/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3291 - accuracy: 0.8643
Epoch 81/100
8000/8000 [==============================] - 1s 90us/sample - loss: 0.3289 - accuracy: 0.8658
Epoch 82/100
8000/8000 [==============================] - 1s 81us/sample - loss: 0.3287 - accuracy: 0.8641
Epoch 83/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3286 - accuracy: 0.8670
Epoch 84/100
8000/8000 [==============================] - 1s 93us/sample - loss: 0.3290 - accuracy: 0.8656
Epoch 85/100
8000/8000 [==============================] - 0s 48us/sample - loss: 0.3285 - accuracy: 0.8645
Epoch 86/100
8000/8000 [==========================

**3. Evaluating the Model**

In [29]:
y_predict = ann.predict(x_test)
y_predict[:6]

array([[0.2934221 ],
       [0.22921829],
       [0.1813158 ],
       [0.05655058],
       [0.04512191],
       [0.91699463]], dtype=float32)

In [30]:
# Change probability to binary value
y_predict = (y_predict > 0.5)
np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)), 1)

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix

In [35]:
tn, fp, fn, tp = confusion_matrix(y_test, y_predict).ravel()
confusion_matrix(y_test, y_predict)

array([[1512,   83],
       [ 192,  213]], dtype=int64)

In [38]:
accuracy = (tn + tp) / (tn + fp + fn + tp)
precision = tp / (fp + tp)
recall = tp / (fn + tp)
f1_score = (2 * precision * recall) / (precision + recall)

In [39]:
print('Accuracy: {}'.format(accuracy))
print('Precision: {}'.format(precision))
print('Recall: {}'.format(recall))
print('F1 Score: {}'.format(f1_score))

Accuracy: 0.8625
Precision: 0.7195945945945946
Recall: 0.5259259259259259
F1 Score: 0.6077032810271041
